spring:
  application:
    name: letsgo

  datasource:
    url: jdbc:postgresql://localhost:5432/letsgo
    username: letsgo
    password: letsgo123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # схему управляет Flyway!
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 60MB

server:
  port: 8080

# Куда складываются фото альбома воспоминаний
app:
  upload-dir: uploads

# ЛОГИРОВАНИЕ
logging:
  level:
    root: INFO
    ru.top.events: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/letsgo.log